### ISSUE TITLE
Question: AWS S3 Integration

### ISSUE THREAD

**Issue by arunkumar-muthusamy** [adrichem/artifact-store#1]
Hi,

Do you have any suggestion on AWS S3 integration?

Thanks!

**Comment by karthikgreentrend** [comment]
i am also looking for S3 @arunkumar-muthusamy 
did you or anyone came with a solution

**Comment by karthikgreentrend** [comment]
https://github.com/qakart/artifact-store-s3

**Comment by karthikgreentrend** [comment]
@arunkumar-muthusamy please use the above repo

**Comment by arunkumar-muthusamy** [comment]
Thank you @qakart! Appreciate your help!!
